### ISSUE TITLE
Cannot execute the test file

### ISSUE THREAD

**Issue by LucaBastelt** [metafetish/liblovense-py#8]
I connected the device via bluetooth and created a /dev/rfcomm0 device for communication. But when I start the example via python I get this output:

```
Traceback (most recent call last):

  File "examples/get_device_info.py", line 1, in <module>

    from lovesense.comm import LovenseSyncSerial

ImportError: cannot import name LovenseSyncSerial
```

How do I solve this? I know I probably just forgot to install one small thing, but I just can't find it

**Comment by qdot** [comment]
That's my fault. It's named wrong, should be LovesenseSerialSync. See issue #6. Will try to get that fixed asap but for now changing that should fix it for you.

**Comment by LucaBastelt** [comment]
Oh sweet :D thanks

**Comment by LucaBastelt** [comment]
Well, the s.open line throws an not-implemented error and the LovesenseSerialSync Init takes the serial port as an argument, so thats not working either.
 But even if I corret that I still get an error, this time a Bluetooth connection problem. Is this also a known problem?


```
  File "examples/get_device_info.py", line 8, in main
    status = s.readStatus()
  File "/usr/local/lib/python2.7/dist-packages/lovesense/base.py", line 52, in readStatus
    ch = self.readCharacter()
  File "/usr/local/lib/python2.7/dist-packages/lovesense/comm.py", line 29, in readCharacter
    return self.port.read()
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 495, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

```

**Comment by qdot** [comment]
Hmm. Was the toy connected already when running that? Sounds like something might have gotten stuck open.

**Comment by LucaBastelt** [comment]
It seems to be a [known python bug](https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/1501240). I've switched to the nodejs implementation now, which says
opening!
setting vibrate speed!
and then just queitly exits. So much sadness all around :D

**Comment by LucaBastelt** [comment]
Could my issue have anything to do with the fact that I can only connect, but not pair my laptop with the lush?

I always get this message on pairing with bluetoothctl:
```
[CHG] Device E9:EB:FF:94:42:AC Connected: no
Failed to pair: org.bluez.Error.AuthenticationCanceled

```

**Comment by qdot** [comment]
That's weird. I thought you'd already had to pair in order to see the /dev/rfcomm0 device? BTW what distro/kernel version/bluez version are you on?

**Comment by qdot** [comment]
Also note that the non-hush portions of the library have seen very little testing (most users so far are interested in the hush, which is BLE), so you're unfortunately on a bit of a bleeding edge release here. :)

**Comment by LucaBastelt** [comment]
I'm on Linux Mint 18.1 Serena
using bluez 5.37-0ubuntu5

To connect to the device I use bluetoothctl.
I do power on, agent on, scan on, and then connect <device>
Then I use rfcomm bind 0 <device> to get the serial device.
If I use pair <device> it fails as described above.

**Comment by qdot** [comment]
Ok. I'll try testing this myself later if I get time. I know I've gotten it working before (wouldn't have put the library up if it didn't work, heh) but it's been months.

If I'm taking too long, poke me. :)

**Comment by LucaBastelt** [comment]
That'd be great, thanks :)
I'll keep on trying myself, lets see who gets a solution first ;)

**Comment by kamita721** [comment]
>  always get this message on pairing with bluetoothctl:
> [CHG] Device E9:EB:FF:94:42:AC Connected: no
> Failed to pair: org.bluez.Error.AuthenticationCanceled

I saw the same error. This appears to be a problem on the bluetoothctl side of things. After pairing with bluetoothctl I was able to connect with "sudo rfcomm bind rfcomm0 DC:0D:30:00:C4:2C".

Running the example triggered a NOT IMPLEMENTED error in base.py, but I was able to confirm device connectivity by writing to /dev/rfcomm directly.

**Comment by valuta1995** [comment]
I was able to connect using:
`sudo rfcomm bind 0 <addr>`

However running s.deviceType() throws the following error.
`SerialException: write failed: [Errno 5] Input/output error`

Edit1: I first connected the device (lush) in bluetoothctl. Writing to the device through /service0009/char000d works.

Edit2: Attempting to pair in bluetoothctl causes the lush to crash? (shuts itself down)

**Comment by qdot** [comment]
rfcomm won't work on anything but the max and nora. Those are the only 2 toys that support bluetooth 2/4. This library needs to support Bluetooth 4, and I'm hoping to get to that soon.

**Comment by qdot** [comment]
BTW if someone else wants to work on that and submit PR's, that'd be totally awesome. :D

**Comment by qdot** [comment]
Project shutting down as we now support Lovense toys in https://github.com/buttplugio/buttplug, closing bug as WONTFIX
